/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import ui.ResumenForm;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author anl1.sui
 */
public class PedidoForm extends javax.swing.JFrame {

    private String [] tiposMedicamentos = {"Seleccione..","Analgésico", "Anestésico","Ansiolítico",
    "Antibiótico" , "Anticolinérgico", "Anticonceptivo", "Anticonvulsivo", 
    "Antidpresivo", "Antidiabético", "Antiemético", "Antihelmíntico", "Antihipertensivo",
    "Antihistamínico", "Antineoplásico", "Antiinflamatorio", "Antiparkinsoniano",
    "Antimicótico", "Antipirético", "Antipsicótico", "Antitusivo",
    "Antídoto", "Broncodilatador", "Cardiotónico", "Citostático", "Hipnótico",
    "Hormonoterápico", "Quimioterápico", "Relajante muscular"};
    /**
     * Creates new form PedidoForm
     */
    public PedidoForm() {
        initComponents();
        this.ocultarAdvertencias();
        this.llenarTiposMedicamentos();
         this.radioButonCemefar.setActionCommand("Cemefar");
        this.radiosDistribuidor.add(radioButonCemefar);
        this.radioButtonCofarma.setActionCommand("Cofarma");
        this.radiosDistribuidor.add(radioButtonCofarma);
        this.radioButtonEmpsephar.setActionCommand("Empsephar");
        this.radiosDistribuidor.add(radioButtonEmpsephar);
        this.checkPrincipal.setActionCommand("Principal");   
        this.checkSecundaria.setActionCommand("Secundaria");
        this.chechkGroup.add(this.checkPrincipal);
        this.chechkGroup.add(this.checkSecundaria);
             
    
    }
    private void ocultarAdvertencias (){
        this.labelNombre.setVisible(false);
        this.labelCantidad.setVisible(false);
        this.labelDistribuidor.setVisible(false);
        this.labelTipo.setVisible(false);
        this.labelSucrusal.setVisible(false);
        this.labelNumero.setVisible(false);
    }
    private void llenarTiposMedicamentos() {
        this.comboBoxTipoMed.setModel(new DefaultComboBoxModel<> (this.tiposMedicamentos));
    }
    
    private boolean isNumero(String cadena) {
        return cadena != null && cadena.matches("[0-9.]+");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radiosDistribuidor = new javax.swing.ButtonGroup();
        chechkGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFiedlNombreMed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboBoxTipoMed = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        textFieldCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        radioButtonCofarma = new javax.swing.JRadioButton();
        radioButtonEmpsephar = new javax.swing.JRadioButton();
        radioButonCemefar = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        buttonBorrar = new javax.swing.JButton();
        buttonConfirma = new javax.swing.JButton();
        labelNombre = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        labelSucrusal = new javax.swing.JLabel();
        labelDistribuidor = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        checkPrincipal = new javax.swing.JCheckBox();
        checkSecundaria = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setText("NUEVO PEDIDO");

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/44844_aid_first_health_kit_medicine_icon.png"))); // NOI18N

        jLabel2.setText("Nombre del medicamento:");

        textFiedlNombreMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFiedlNombreMedActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de medicamento:");

        comboBoxTipoMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoMedActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad:");

        jLabel5.setText("Distribuidor");

        radioButtonCofarma.setText("Cofarma");
        radioButtonCofarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCofarmaActionPerformed(evt);
            }
        });

        radioButtonEmpsephar.setText("Empsephar");

        radioButonCemefar.setText("Cemefar");

        jLabel6.setText("Sucursal");

        buttonBorrar.setText("Borrar");
        buttonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarActionPerformed(evt);
            }
        });

        buttonConfirma.setBackground(new java.awt.Color(51, 153, 255));
        buttonConfirma.setText("Confirmar");
        buttonConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmaActionPerformed(evt);
            }
        });

        labelNombre.setForeground(new java.awt.Color(255, 51, 51));
        labelNombre.setText("*Este campo es requerido");

        labelTipo.setForeground(new java.awt.Color(255, 51, 51));
        labelTipo.setText("*Este campo es requerido");

        labelCantidad.setForeground(new java.awt.Color(255, 51, 51));
        labelCantidad.setText("*Este campo es requerido");

        labelSucrusal.setForeground(new java.awt.Color(255, 51, 51));
        labelSucrusal.setText("*Este campo es requerido");

        labelDistribuidor.setForeground(new java.awt.Color(255, 51, 51));
        labelDistribuidor.setText("*Este campo es requerido");

        labelNumero.setForeground(new java.awt.Color(255, 0, 51));
        labelNumero.setText("*El valor debe ser un número");

        checkPrincipal.setText("Principal");
        checkPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPrincipalActionPerformed(evt);
            }
        });

        checkSecundaria.setText("Secundaria");
        checkSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSecundariaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(labelLogo)
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelTipo))
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNombre)
                                .addComponent(comboBoxTipoMed, javax.swing.GroupLayout.Alignment.LEADING, 0, 374, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFiedlNombreMed, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCantidad))
                            .addComponent(labelNumero)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioButtonCofarma)
                                    .addComponent(radioButonCemefar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelDistribuidor))
                                    .addComponent(radioButtonEmpsephar))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelSucrusal))
                                    .addComponent(checkPrincipal)
                                    .addComponent(checkSecundaria)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(buttonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonConfirma)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(labelLogo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFiedlNombreMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNombre)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxTipoMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTipo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCantidad))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNumero)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelDistribuidor)
                    .addComponent(jLabel6)
                    .addComponent(labelSucrusal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonCofarma)
                    .addComponent(checkPrincipal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonEmpsephar)
                    .addComponent(checkSecundaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButonCemefar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBorrar)
                    .addComponent(buttonConfirma))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonCofarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCofarmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonCofarmaActionPerformed

    private void buttonConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmaActionPerformed
      
        boolean errores = false;
      
        if (textFiedlNombreMed.getText()==null || textFiedlNombreMed.getText()
              .isEmpty()) {
          this.labelNombre.setVisible(true);
          errores = true;
          
      }
      if (this.textFieldCantidad.getText() == null || this.textFieldCantidad.getText().isEmpty()) {
          this.labelCantidad.setVisible(true);
          errores = true;
      }
      if (this.radiosDistribuidor.getSelection()==null){
          this.labelDistribuidor.setVisible(true);
          errores = true;
      }

       if (this.chechkGroup.getSelection()==null) {
            this.labelSucrusal.setVisible(true);
          errores = true;
       }

         if (this.comboBoxTipoMed.getSelectedIndex()==0) {
             this.labelTipo.setVisible(true);
             errores = true;
         }
         if (!this.textFieldCantidad.getText().isEmpty() 
                 && !this.isNumero(this.textFieldCantidad.getText())) {
             this.labelNumero.setVisible(true);
             errores = true;
         }
         if (!errores) {
             ResumenForm resumenForm = new ResumenForm();
             resumenForm.setLabelDist(this.radiosDistribuidor.getSelection().getActionCommand());
             resumenForm.setLabelUnidades(this.textFieldCantidad.getText(),
                     this.comboBoxTipoMed.getSelectedItem().toString(),
                     this.textFiedlNombreMed.getText());
             resumenForm.setLabelResumenSucursal(this.chechkGroup.getSelection().getActionCommand());
             resumenForm.setVisible(true);
             resumenForm.setLocationRelativeTo(null);
             this.setVisible(false);
             
         }
    }//GEN-LAST:event_buttonConfirmaActionPerformed

    private void comboBoxTipoMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoMedActionPerformed
        
        
    }//GEN-LAST:event_comboBoxTipoMedActionPerformed

    private void textFiedlNombreMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFiedlNombreMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFiedlNombreMedActionPerformed

    private void buttonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarActionPerformed
        this.textFiedlNombreMed.setText("");
        this.textFieldCantidad.setText("");
        this.comboBoxTipoMed.setSelectedIndex(0);
        this.radiosDistribuidor.clearSelection();
        this.chechkGroup.clearSelection();
        this.ocultarAdvertencias();
    }//GEN-LAST:event_buttonBorrarActionPerformed

    private void checkPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPrincipalActionPerformed
        
        if(this.checkSecundaria.isSelected()) {
            this.checkSecundaria.setSelected(false);
        }
    }//GEN-LAST:event_checkPrincipalActionPerformed

    private void checkSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSecundariaActionPerformed
         if(this.checkPrincipal.isSelected()) {
            this.checkPrincipal.setSelected(false);
        }
    }//GEN-LAST:event_checkSecundariaActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBorrar;
    private javax.swing.JButton buttonConfirma;
    private javax.swing.ButtonGroup chechkGroup;
    private javax.swing.JCheckBox checkPrincipal;
    private javax.swing.JCheckBox checkSecundaria;
    private javax.swing.JComboBox<String> comboBoxTipoMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelDistribuidor;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelSucrusal;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JRadioButton radioButonCemefar;
    private javax.swing.JRadioButton radioButtonCofarma;
    private javax.swing.JRadioButton radioButtonEmpsephar;
    private javax.swing.ButtonGroup radiosDistribuidor;
    private javax.swing.JTextField textFiedlNombreMed;
    private javax.swing.JTextField textFieldCantidad;
    // End of variables declaration//GEN-END:variables
}
